[project]
name = 'Decentralized-Specialized-Healthcare-Transportation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.driver-verification]
path = 'contracts/driver-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.medical-equipment]
path = 'contracts/medical-equipment.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-registration]
path = 'contracts/patient-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
